# Generated by Django 5.2.4 on 2025-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psysmysql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerselldetail',
            name='quantity_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
